# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop and https://repo.codemc.io/#browse/browse:relativitymc:org%2Frelativitymc%2Fmodern-yarn
mc_version=26.3
yarn_mappings=26.3+build.1
loader_version=0.19.3

# Mod Properties
mod_version=0.0.1
maven_group=io.github.eat-ram.reflog
archives_base_name=reflog

# Dependencies
fabric_api_version=0.161.0+26.3
