alias.awl=minecraft:empty;minecraft:water|falling=false;minecraft:lava|falling=false
modify_existing.override.net.minecraft.world.level.block.AmethystClusterBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.AnvilBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.AttachedStemBlock=fluidlogged;minecraft:empty;minecraft:water|falling=false
modify_existing.override.net.minecraft.world.level.block.BannerBlock=fluidlogged;minecraft:empty;minecraft:water|falling=false
modify_existing.override.net.minecraft.world.level.block.BarrierBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.BeaconBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.BedBlock=fluidlogged;minecraft:empty;minecraft:water|falling=false
modify_existing.override.net.minecraft.world.level.block.BellBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.BrewingStandBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.ButtonBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.CalibratedSculkSensorBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.CarpetBlock=fluidlogged;minecraft:empty;minecraft:water|falling=false
modify_existing.override.net.minecraft.world.level.block.CauldronBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.ChainBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.ComparatorBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.ComposterBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.CopperChestBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.CopperGolemStatueBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.DaylightDetectorBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.DetectorRailBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.DoorBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.EnchantingTableBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.EnderChestBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.EndRodBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.FenceGateBlock=fluidlogged;minecraft:empty;minecraft:water|falling=false
modify_existing.override.net.minecraft.world.level.block.GrindstoneBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.HeavyCoreBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.HopperBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.IronBarsBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.LanternBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.LavaCauldronBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.LayeredCauldronBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.LecternBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.LeverBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.LightningRodBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.PiglinWallSkullBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.PlayerHeadBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.PlayerWallHeadBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.PointedDripstoneBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.PoweredRailBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.PressurePlateBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.RailBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.RedstoneTorchBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.RedstoneWallTorchBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.RedstoneWireBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.RepeaterBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.SculkSensorBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.SculkShriekerBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.SculkVeinBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.SkullBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.SlabBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.SpawnerBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.StainedGlassBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.StainedGlassPaneBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.StairBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.StonecutterBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.StrawBedBlock=fluidlogged;minecraft:empty;minecraft:water|falling=false
modify_existing.override.net.minecraft.world.level.block.SugarCaneBlock=fluidlogged;minecraft:empty;minecraft:water|falling=false
modify_existing.override.net.minecraft.world.level.block.SulfurSpikeBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.TintedGlassBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.TrapDoorBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.TrialSpawnerBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.TripWireBlock=fluidlogged;minecraft:empty;minecraft:water|falling=false
modify_existing.override.net.minecraft.world.level.block.TripWireHookBlock=fluidlogged;minecraft:empty;minecraft:water|falling=false
modify_existing.override.net.minecraft.world.level.block.WallBannerBlock=fluidlogged;minecraft:empty;minecraft:water|falling=false
modify_existing.override.net.minecraft.world.level.block.WallBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.WallSkullBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.WeatheringCopperBarsBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.WeatheringCopperChainBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.WeatheringCopperChestBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.WeatheringCopperDoorBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.WeatheringCopperGolemStatueBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.WeatheringCopperGrateBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.WeatheringCopperSlabBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.WeatheringCopperStairBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.WeatheringCopperTrapDoorBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.WeatheringLanternBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.WeatheringLightningRodBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.WeightedPressurePlateBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.WitherSkullBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.WitherWallSkullBlock=fluidlogged;$awl
modify_existing.override.net.minecraft.world.level.block.WoolCarpetBlock=fluidlogged;minecraft:empty;minecraft:water|falling=false
modify_existing.retain_fluids_in.net.minecraft.world.level.block.BarrierBlock=true
modify_existing.retain_fluids_in.net.minecraft.world.level.block.BeaconBlock=true
modify_existing.retain_fluids_in.net.minecraft.world.level.block.LeavesBlock=true
modify_existing.retain_fluids_in.net.minecraft.world.level.block.MangroveLeavesBlock=true
modify_existing.retain_fluids_in.net.minecraft.world.level.block.MangroveRootsBlock=true
modify_existing.retain_fluids_in.net.minecraft.world.level.block.StainedGlassBlock=true
modify_existing.retain_fluids_in.net.minecraft.world.level.block.TintedGlassBlock=true
modify_existing.retain_fluids_in.net.minecraft.world.level.block.TintedParticleLeavesBlock=true
modify_existing.retain_fluids_in.net.minecraft.world.level.block.UntintedParticleLeavesBlock=true
modify_existing.retain_fluids_in.net.minecraft.world.level.block.WeatheringCopperGrateBlock=true